### ISSUE TITLE
Завтрашний баг фикс

### ISSUE THREAD

**Issue by asass81** [MaxStar133/Temka#2]
Есть проблемы со звуками с паузой и код скриптов надо как-то объединять в одни скрипты, а то понос какой-то в одном месте хп в другом - спид, а в 3 - дамаг 
![Диаграмма без названия drawio](https://github.com/MaxStar133/Temka/assets/107756138/ddc67550-9df9-4356-bfd1-f84a58e4d654)

**Comment by MaxStar133** [comment]
Там дохуя возможных багов из-за того что мы удаляем Player когда мы умираем и надо обрабатывать каждый момент в скриптах где мы ссылаемся на player а то пизда игра крашится. Там крч надо замутить как с паузой тип не удалять плеера а то пися пока какашечки @asass81
